id: node.game_list.teaser
uuid: 2157f02a-83cb-4a61-a210-1604bb161efa
targetEntityType: node
bundle: game_list
mode: teaser
content:
  body:
    label: hidden
    type: text_summary_or_trimmed
    weight: -4
    settings:
      trim_length: 600
hidden:
  langcode: true
status: true
