id: node.game_list.default
uuid: 536259c2-b36d-4937-9002-2b63e092bd82
targetEntityType: node
bundle: game_list
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: -4
    settings: {  }
  field_games:
    weight: -3
    label: above
    settings:
      link: true
    type: entity_reference_label
hidden:
  langcode: true
status: true
