id: node.genre.default
uuid: 5e481092-2003-40da-851d-298078edae20
targetEntityType: node
bundle: genre
mode: default
content:
  title:
    type: string
    weight: -5
    settings:
      size: '60'
      placeholder: ''
hidden:
  body: true
status: true
