id: node.board_game.default
uuid: 2409f7bd-9b2d-4e46-8500-b1e206bcb1cb
targetEntityType: node
bundle: board_game
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: -4
    settings: {  }
  field_person:
    weight: -3
    label: above
    settings:
      link: true
    type: entity_reference_label
  field_publisher:
    weight: -2
    label: above
    settings:
      link: true
    type: entity_reference_label
  field_genre:
    weight: -1
    label: above
    settings:
      link: true
    type: entity_reference_label
  field_release_date:
    weight: 0
    label: above
    settings:
      format_type: medium
    type: datetime_default
  field_image:
    weight: 1
    label: above
    settings:
      image_style: ''
      image_link: ''
    type: image
  field_player_num:
    weight: 2
    label: above
    settings:
      thousand_separator: ''
      prefix_suffix: true
    type: number_integer
  field_play_time:
    weight: 3
    label: above
    settings: {  }
    type: text_default
hidden:
  langcode: true
  field_designer: true
status: true
