id: node.developer.default
uuid: 31541104-51a3-49f4-ac00-a0aca20819dd
targetEntityType: node
bundle: developer
mode: default
content:
  title:
    type: string
    weight: -5
    settings:
      size: '60'
      placeholder: ''
  field_logo:
    weight: -3
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    type: image_image
hidden:
  body: true
status: true
