id: node.publisher.field_logo
uuid: 56e40928-ef92-409a-8e00-dce983eca4ac
status: true
langcode: en
field_uuid: 57220fad-5943-4294-be00-cbcf8a259491
field_name: field_logo
entity_type: node
bundle: publisher
label: Logo
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  file_directory: image/logo
  file_extensions: 'png gif jpg jpeg'
  max_filesize: ''
  max_resolution: ''
  min_resolution: ''
  alt_field: false
  alt_field_required: false
  title_field: false
  title_field_required: false
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
field_type: image
