id: node.board_game.body
uuid: 73c225e6-c355-4ae3-af00-fa63ec00b053
status: true
langcode: en
field_uuid: 2603d718-1cb9-46a5-9a09-9b05205fc861
field_name: body
entity_type: node
bundle: board_game
label: 'Short description'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  text_processing: true
  display_summary: false
field_type: text_with_summary
