id: node.board_game.field_release_date
uuid: ddfcf645-c0dc-4def-b900-0d81169979a3
status: true
langcode: en
field_uuid: 6df18d6d-8e5c-4c2a-a300-b1bcc85dce6e
field_name: field_release_date
entity_type: node
bundle: board_game
label: 'Release date'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings: {  }
field_type: datetime
