id: node.field_person
uuid: 45543e57-054f-4ec3-9a05-5c5366b785da
status: true
langcode: en
name: field_person
entity_type: node
type: entity_reference
settings:
  target_type: node
module: entity_reference
locked: false
cardinality: -1
translatable: false
indexes: {  }
