id: node.field_publisher
uuid: 86085263-d15f-4f1f-8f00-aa4281839c8e
status: true
langcode: en
name: field_publisher
entity_type: node
type: entity_reference
settings:
  target_type: node
module: entity_reference
locked: false
cardinality: -1
translatable: false
indexes: {  }
