type: genre
name: Genre
description: ''
help: ''
has_title: true
title_label: Name
settings:
  node:
    preview: 1
    options:
      status: true
      revision: true
      promote: false
      sticky: false
    submitted: false
status: true
uuid: f1681e91-4245-42ac-aa00-fe55bd244bba
langcode: en
