type: video_game
name: 'Video game'
description: ''
help: ''
has_title: true
title_label: Name
settings:
  node:
    preview: 1
    options:
      status: true
      revision: true
      promote: false
      sticky: false
    submitted: false
status: true
uuid: 4d5e550a-7b30-4d90-8f04-4c01280b25e1
langcode: en
