id: node.person.default
uuid: b0ef91dd-ab74-4e83-9007-7a12aff56305
targetEntityType: node
bundle: person
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: -4
    settings: {  }
hidden:
  langcode: true
status: true
