id: node.person.default
targetEntityType: node
bundle: person
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: -4
    settings: {  }
hidden:
  langcode: true
status: true
