id: node.developer.default
targetEntityType: node
bundle: developer
mode: default
content:
  field_logo:
    weight: -3
    label: above
    settings:
      image_style: ''
      image_link: ''
    type: image
  body:
    label: hidden
    type: text_default
    weight: -2
    settings: {  }
hidden:
  langcode: true
status: true
