id: node.publisher.default
uuid: a3e5becc-23d8-4583-8f0f-159e26e0b68d
targetEntityType: node
bundle: publisher
mode: default
content:
  field_logo:
    weight: -4
    label: above
    settings:
      image_style: ''
      image_link: ''
    type: image
  body:
    label: hidden
    type: text_default
    weight: -3
    settings: {  }
hidden:
  langcode: true
status: true
