id: node.genre.teaser
targetEntityType: node
bundle: genre
mode: teaser
content:
  body:
    label: hidden
    type: text_summary_or_trimmed
    weight: -4
    settings:
      trim_length: 600
hidden:
  langcode: true
status: true
