id: node.genre.teaser
uuid: aca83800-01a2-4593-a612-187ae8259a17
targetEntityType: node
bundle: genre
mode: teaser
content:
  body:
    label: hidden
    type: text_summary_or_trimmed
    weight: -4
    settings:
      trim_length: 600
hidden:
  langcode: true
status: true
