id: node.publisher.default
targetEntityType: node
bundle: publisher
mode: default
content:
  title:
    type: string
    weight: -5
    settings:
      size: '60'
      placeholder: ''
  field_logo:
    weight: -4
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    type: image_image
  body:
    type: text_textarea_with_summary
    weight: -3
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
hidden: {  }
status: true
