id: node.field_genre
status: true
langcode: en
name: field_genre
entity_type: node
type: entity_reference
settings:
  target_type: node
module: entity_reference
locked: false
cardinality: -1
translatable: false
indexes: {  }
