id: node.video_game.body
status: true
langcode: en
field_name: body
entity_type: node
bundle: video_game
label: 'Short description'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  text_processing: true
  display_summary: false
field_type: text_with_summary
