id: node.field_player_num
uuid: 80ce6873-ff1a-4a6d-8400-fa721c6792d8
status: true
langcode: en
name: field_player_num
entity_type: node
type: integer
settings: {  }
module: Core
locked: false
cardinality: 1
translatable: false
indexes: {  }
