id: node.publisher.body
uuid: ba0db367-114f-43a4-8700-b401116ed6ed
status: true
langcode: en
field_uuid: 2603d718-1cb9-46a5-9a09-9b05205fc861
field_name: body
entity_type: node
bundle: publisher
label: Body
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  display_summary: true
  text_processing: true
field_type: text_with_summary
