id: node.video_game.field_tags
status: true
langcode: en
field_name: field_tags
entity_type: node
bundle: video_game
label: Tags
description: ''
required: false
default_value: {  }
default_value_function: ''
settings: {  }
field_type: taxonomy_term_reference
