id: node.field_play_time
status: true
langcode: en
name: field_play_time
entity_type: node
type: text
settings:
  max_length: 255
module: text
locked: false
cardinality: 1
translatable: false
indexes: {  }
