id: node.game_list.body
status: true
langcode: en
field_name: body
entity_type: node
bundle: game_list
label: Description
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  text_processing: true
  display_summary: false
field_type: text_with_summary
