id: node.body
uuid: 2603d718-1cb9-46a5-9a09-9b05205fc861
status: true
langcode: en
name: body
entity_type: node
type: text_with_summary
settings: {  }
module: text
locked: false
cardinality: 1
translatable: false
indexes: {  }
