format: full_html
name: 'Full HTML'
weight: 1
cache: true
status: true
uuid: edaa28cb-6e30-4274-9a00-c87390eed0a1
langcode: en
filters:
  filter_caption:
    id: filter_caption
    provider: filter
    status: true
    weight: 9
    settings: {  }
  filter_htmlcorrector:
    id: filter_htmlcorrector
    provider: filter
    status: true
    weight: 10
    settings: {  }
  filter_autop:
    id: filter_autop
    provider: filter
    status: false
    weight: 0
    settings: {  }
  filter_html:
    id: filter_html
    provider: filter
    status: false
    weight: -10
    settings:
      allowed_html: '<a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd> <h4> <h5> <h6>'
      filter_html_help: true
      filter_html_nofollow: false
  filter_html_escape:
    id: filter_html_escape
    provider: filter
    status: false
    weight: -10
    settings: {  }
  filter_html_image_secure:
    id: filter_html_image_secure
    provider: filter
    status: false
    weight: 9
    settings: {  }
  filter_url:
    id: filter_url
    provider: filter
    status: false
    weight: 0
    settings:
      filter_url_length: 72
