type: publisher
name: Publisher
description: ''
help: ''
has_title: true
title_label: Name
settings:
  node:
    options:
      status: true
      promote: false
      sticky: false
      revision: true
    preview: 1
    submitted: false
status: true
uuid: fa03fb40-bca4-426e-9906-6f06547166fd
langcode: en
