type: board_game
name: 'Board game'
description: ''
help: ''
has_title: true
title_label: Name
settings:
  node:
    options:
      status: true
      promote: false
      sticky: false
      revision: true
    preview: 1
    submitted: false
status: true
langcode: en
